on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-20.04
    env:
      GRADLE_BUILD_CACHE_PUSH: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: gradle/gradle-build-action@v1
        with:
          arguments: classes
  update_repository:
    name: Update repository
    runs-on: ubuntu-20.04
    needs: [ build ]
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: rm -rf .git/ # delete .git here to ignore the parent git repo and only care about plugin-repo
      - uses: actions/checkout@v2
        with:
          ref: plugin-repo
          path: ci-repo
      - uses: gradle/gradle-build-action@v1
        with:
          arguments: assemblePlugin buildRepository
      - run: |
          cd ci-repo
          git config --local user.email "actions@github.com"
          git config --local user.name "actions-user"
          git add .
          git commit -m "Update plugin repository"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: plugin-repo # the branch GH pages is on
          directory: ci-repo # the targetDirectory specified above